name: Build

on: [push,pull_request,workflow_dispatch]

env:
  BUILD_TYPE: Release
  DATA_BRANCH: master

jobs:
  build:
    strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: ubuntu-dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install -y gcc-10 g++-10
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 \
          --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
        git clone https://github.com/axboe/liburing.git
        cd liburing && ./configure && make -j6 && sudo make install
        sudo apt-get install libboost-all-dev


    - name: macox-dependencies
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install boost

    - name: windows-dependencies
      if: startsWith(matrix.os, 'windows')
      run: |
        choco install boost-msvc-14.1


    - name: dependencies
      run: |
        python3 -m pip install --upgrade pip
        cmake -E make_directory ${{ github.workspace }}/build

    - name: configure cmake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{ github.workspace }}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

